apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  DATABASE_HOST: mariadb-internal-service 
  DATABASE_PASSWORD : greencodr
  DATABASE_NAME : testdb
  DATABASE_USER: root

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-internal-service
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306


---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: mariadb
  type: LoadBalancer # port type
  ports:
    - protocol: TCP
      port: 8000 # same port of a service as for a pods
      targetPort: 8000 # targeting containerPort
      nodePort: 30105 # external IP port from 30000 till 32767 range
---
apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: mariadb-deployment
spec: # specification for deployment resource
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for Pods
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306 
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: DATABASE_PASSWORD
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: DATABASE_NAME
      - name: django
        imagePullPolicy: Never
        image: django-sample 
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: DATABASE_HOST
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: DATABASE_NAME
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: DATABASE_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: DATABASE_PASSWORD